pipelines:
  - name: affinity_group_pipeline
    steps:
      - name: agp_s1
        type: Bash
        configuration:
          affinityGroup: agp_container
        execution:
          onExecute:
            # Generate random container name
            - RAND_ID=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 8)
            - CONT_NAME="alpine-$RAND_ID"
            - echo "Container name $CONT_NAME"
            - add_run_variables container_name=$CONT_NAME
            # Create container
            - docker run -d --name $CONT_NAME alpine

      - name: agp_s2
        type: Bash
        configuration:
          affinityGroup: agp_container
          inputSteps:
            - name: agp_s1
        execution:
          onExecute:
            # Get run container name
            - echo "Container name $container_name"
            # Count container by name
            # Count should be equals 1 since container was created by previous step on same affinity group
            - COUNT=$(docker ps -aq -f name=$container_name | wc -l)
            - echo "Count $COUNT"
            - |
              [[ "$COUNT" == "1" ]]
            # Delete container
            - docker rm -fv $container_name

  - name: non_affinity_group_pipeline
    steps:
      - name: nagp_s1
        type: Bash
        execution:
          onExecute:
            # Generate random container name
            - RAND_ID=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 8)
            - CONT_NAME="alpine-$RAND_ID"
            - echo "Container name $CONT_NAME"
            - add_run_variables container_name=$CONT_NAME
            # Create container
            - docker run -d --name $CONT_NAME alpine

          - name: nagp_s2
            type: Bash
            configuration:
              inputSteps:
                - name: nagp_s1
            execution:
              onExecute:
                # Get run container name
                - echo "Container name $container_name"
                # Count container by name
                # Count should be equals 0 since container was created by previous step on different affinity group
                - COUNT=$(docker ps -aq -f name=$container_name | wc -l)
                - echo "Count $COUNT"
                - |
                  [[ "$COUNT" == "0" ]]