pipelines:
  - name: helm_blue_green_pipeline
    steps:
      - name: helm_blue_green_deploy
        type: HelmBlueGreenDeploy
        configuration:
          environmentVariables:
            my-env: value
