resources:
  - name: helm_bluegreen_gitrepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: elioengcomp/jfrog-pipelines-simple-example
      branches:
        include: helm-bluegreen-poc

  - name: helm_bluegreen_app_image
    type: Image
    configuration:
      registry: my_artifactory
      sourceRepository: my-docker_local
      imageName: f5760.jfrog-pipelines.com/my-docker-local/app
      imageTag: latest
      autoPull: true

  - name: helm_bluegreen_app_chart
    type: HelmChart
    configuration:
      sourceArtifactory: my_artifactory
      repository: app-helm
      chart: app
      version: 0.0.1

  - name: helm_bluegreen_docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: my_artifactory
      buildName: helm_bluegreen_poc_image
      buildNumber: 1

  - name: helm_bluegreen_helm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: my_artifactory
      buildName: helm_bluegreen_poc_chart
      buildNumber: 1

pipelines:
  - name: helm_bluegreen_poc
    steps:
      - name: trigger_new_build
        type: Bash
        execution:
          onExecute:
            - echo "Starting new build"
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: app
          dockerFileName: Dockerfile
          dockerImageName: f5760.jfrog-pipelines.com/my-docker-local/app
          dockerImageTag: 0.0.${run_number}
          inputSteps:
            - name: trigger_new_build
          inputResources:
            - name: helm_bluegreen_gitrepo
              trigger: false
          integrations:
            - name: my_artifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: my-docker-local
          integrations:
            - name: my_artifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: helm_bluegreen_app_image
            - name: helm_bluegreen_docker_build_info

      - name: publish_docker_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: helm_bluegreen_docker_build_info

      - name: helm_publish
        type: HelmPublish
        configuration:
          helmVersion: 3
          chartPath: "./chart/app"
          lint: true
          autoPublishBuildInfo: true
          inputSteps:
            - name: publish_docker_build
          inputResources:
            - name: helm_bluegreen_gitrepo
              trigger: false
          outputResources:
            - name: helm_bluegreen_app_chart
            - name: helm_bluegreen_helm_build_info
        execution:
          onStart:
            - CHART_VERSION=0.0.$run_number
            - pushd $res_helm_bluegreen_gitrepo_resourcePath/chart/app
            - "sed -ie \"s/^version: .*$/version: $CHART_VERSION/\" Chart.yaml"
            - "sed -ie \"s/^appVersion: .*$/appVersion: $CHART_VERSION/\" Chart.yaml"
            - popd

      - name: helm_deploy
        type: HelmDeploy
        configuration:
          helmVersion: 3
          releaseName: apptest
          flags: "--set image.registry='f5760.jfrog-pipelines.com/my-docker'"
          inputSteps:
            - name: helm_publish
          integrations:
            - name: my_k8s
          inputResources:
            - name: helm_bluegreen_app_chart

  - name: test
    steps:
      - name: test
        type: Bash
        execution:
          onExecute:
            - which yq