resources:
  - name: chart
    type: HelmChart
    configuration:
      sourceArtifactory: my_art
      repository: helm
      chart: app
      version: 0.0.0

pipelines:
  - name: helm_blue_green_pipeline
    steps:
      - name: helm_blue_green_deploy
        type: HelmBlueGreenDeploy
        configuration:
          environmentVariables:
            my-env: value
          integrations:
            - name: my_k8s
          inputResources:
            - name: chart
