pipelines:

  - name: my_broken_host_pipeline
    steps:
      - name: delete_tmp_folder
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - rm -rf /tmp
      - name: show_message
        type: Bash
        configuration:
          inputSteps:
            - name: delete_tmp_folder
        execution:
          onExecute:
            - echo "Running"
