resources:
  - name: app_gitrepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: elioengcomp/jfrog-pipelines-simple-example
      branches:
        include: helm-bluegreen-poc

  - name: app_image
    type: Image
    configuration:
      registry: my_art
      sourceRepository: docker-local
      imageName: 192.168.50.2:8082/docker-local/app
      imageTag: latest
      autoPull: true

  - name: app_chart
    type: HelmChart
    configuration:
      sourceArtifactory: my_art
      repository: helm
      chart: app
      version: 0.0.0

pipelines:
  - name: helm_blue_green_pipeline
    steps:

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: app
          dockerFileName: Dockerfile
          dockerImageName: 192.168.50.2:8082/docker-local/app
          dockerImageTag: 0.0.${run_number}
          inputResources:
            - name: app_gitrepo
              trigger: false
          integrations:
            - name: my_art

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: my_art
          inputSteps:
            - name: docker_build
          outputResources:
            - name: app_image

      - name: helm_publish
        type: HelmPublish
        configuration:
          helmVersion: 3
          chartPath: "./chart/app"
          lint: true
          autoPublishBuildInfo: false
          inputSteps:
            - name: docker_push
          inputResources:
            - name: app_gitrepo
              trigger: false
          outputResources:
            - name: app_chart
        execution:
          onStart:
            - CHART_VERSION=0.0.$run_number
            - pushd $res_app_gitrepo_resourcePath/chart/app
            - "sed -ie \"s/^version: .*$/version: $CHART_VERSION/\" Chart.yaml"
            - "sed -ie \"s/^appVersion: .*$/appVersion: $CHART_VERSION/\" Chart.yaml"
            - popd

      - name: helm_blue_green_deploy
        type: HelmBlueGreenDeploy
        configuration:
          helmVersion: 3
          namespace: pipe-master-pool
          blueReleaseName: app-blue
          blueFlags: "--set env=blue"
          greenReleaseName: app-green
          greenFlags: "--set env=green"
          roleServices:
            - blueReferenceName: app-blue-app
              greenReferenceName: app-green-app
              idleName: app-idle-service
              liveName: app-service
            - blueReferenceName: app-blue-app
              greenReferenceName: app-green-app
              idleName: app-idle-service-2
              liveName: app-service-2
          environmentVariables:
            myenv: "value"
          integrations:
            - name: my_k8s
          inputResources:
            - name: app_chart
              trigger: false
