resources:
  - name: app_gitrepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: elioengcomp/jfrog-pipelines-simple-example
      branches:
        include: helm-bluegreen-poc

  - name: app_docker_build_info
      type: BuildInfo
      configuration:
        sourceArtifactory: s_artifactory

pipelines:
  - name: docker_example
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NUMBER: ${run_id}

    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: app
          dockerFileName: Dockerfile
          dockerImageName: ${artifactory_registry_url}/docker-local/app
          dockerImageTag: ${run_id}
          inputResources:
            - name: app_gitrepo
              trigger: false
          integrations:
            - name: s_artifactory
          execution:
            onStart:
              - artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          autoPublishBuildInfo: true
          integrations:
            - name: s_artifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: app_docker_build_info

