resources:
  - name: chart
    type: HelmChart
    configuration:
      sourceArtifactory: my_art
      repository: helm
      chart: app
      version: 0.0.0

pipelines:
  - name: helm_blue_green_pipeline
    steps:
      - name: helm_blue_green_deploy
        type: HelmBlueGreenDeploy
        configuration:
          helmVersion: 3
          namespace: pipe-master-pool
          blueReleaseName: app-blue
          greenReleaseName: app-green
          roleServices:
            - blueReferenceName: app-blue-service
              greenReferenceName: app-green-service
              idleName: app-idle-service
              liveName: app-service
            - blueReferenceName: app-blue-service
              greenReferenceName: app-green-service
              idleName: app-idle-service-2
              liveName: simplehelm-generic-3
          environmentVariables:
            myenv: "value"
          integrations:
            - name: my_k8s
          inputResources:
            - name: chart
