resources:
  - name: app_gitrepo
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: elioengcomp/jfrog-pipelines-simple-example
      branches:
        include: helm-bluegreen-poc

  - name: app_image
    type: Image
    configuration:
      registry: another_artifactory
      sourceRepository: docker-local
      imageName: testpsdockerpush.jfrogdev.org/docker-local/app
      imageTag: latest
      autoPull: true

pipelines:
  - name: docker_example
    steps:

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: app
          dockerFileName: Dockerfile
          dockerImageName: testpsdockerpush.jfrogdev.org/docker-local/app
          dockerImageTag: 0.0.${run_number}
          inputResources:
            - name: app_gitrepo
              trigger: false
          integrations:
            - name: another_artifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: another_artifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: app_image

