template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
  - name: PIPE_3727_1
    configuration:
      environmentVariables:
        readOnly:
          pipe_env: pipe_value
          pipe_env_default:
            default: pipe_default_value
    steps:
      - name: PIPE_3727_1_1
        type: Bash
        configuration:
          environmentVariables:
            step_env_str: text_value
            step_env_num: 1
            step_env_default:
              default: step_default_value
            step_env_default_no_custom:
              default: step_default_no_custom_value
              allowCustom: false
            step_env_default_str_list:
              default: value1
              values:
                - value1
                - value2
                - value3
        execution:
          onExecute:
            - echo $pipe_env
            - echo $pipe_env_default
            - echo $step_env_str
            - echo $step_env_num
            - echo $step_env_default
            - echo $step_env_default_no_custom
            - echo $step_env_default_str_list