resources:
  - name: chart
    type: HelmChart

pipelines:
  - name: helm_blue_green_pipeline
    steps:
      - name: helm_blue_green_deploy
        type: HelmBlueGreenDeploy
        configuration:
          environmentVariables:
            my-env: value
          integrations:
            - name: my_k8s
          inputResources:
            - name: chart
