resources:
  - name: helm_bluegreen_gitrepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: elioengcomp/jfrog-pipelines-simple-example
      branches:
        include: helm-bluegreen-poc

  - name: helm_bluegreen_app_image
    type: Image
    configuration:
      registry: my_artifactory
      sourceRepository: my-docker_local
      imageName: f5760.jfrog-pipelines.com/my-docker-local/app
      imageTag: latest
      autoPull: true

  - name: helm_bluegreen_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: my_artifactory
      buildName: helm_bluegreen_poc
      buildNumber: 1

pipelines:
  - name: helm_bluegreen_poc
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: /app
          dockerFileName: Dockerfile
          dockerImageName: f5760.jfrog-pipelines.com/my-docker-local/app
          dockerImageTag: ${run_number}
          inputResources:
            - name: helm_bluegreen_gitrepo
          integrations:
            - name: my_artifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: my-docker-local
          integrations:
            - name: my_artifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: helm_bluegreen_app_image

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: helm_bluegreen_build_info