resources:
  - name: app_gitrepo
    type: GitRepo
    configuration:
      gitProvider: s_github
      path: elioengcomp/jfrog-pipelines-simple-example
      branches:
        include: helm-bluegreen-poc

  - name: app_image
    type: Image
    configuration:
      registry: s_artifactory
      sourceRepository: docker-local
      imageName: pipelines-eliom-rt.ngrok.io/docker-local/app
      imageTag: latest
      autoPull: true

pipelines:
  - name: helm_blue_green_pipeline
    steps:

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: app
          dockerFileName: Dockerfile
          dockerImageName: pipelines-eliom-rt.ngrok.io/docker-local/app
          dockerImageTag: 0.0.${run_number}
          inputResources:
            - name: app_gitrepo
              trigger: false
          integrations:
            - name: my_art

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: my_art
          inputSteps:
            - name: docker_build
          outputResources:
            - name: app_image

